### ISSUE TITLE
Exception when killing the app while it is requesting something (broken socket-pipe)

### ISSUE THREAD

**Issue by ilendemli** [istornz/iPokeGo#272]
### Crash
```
Exception in thread Thread-119:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/SocketServer.py", line 602, in process_request_thread
    self.handle_error(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 599, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 657, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 716, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 279, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
```

### Steps to reproduce
Start the server, set up the app, wait a few seconds, kill the app, see crash in terminal

### Environment
Raspberry Pi Zero
Debian Jessy
PokemonGo-Map, local branch is at commit 77a4490

**Comment by ilendemli** [comment]
Nevermind, it is not iPokeGo related, reproduced it with the PokemonGo-Map webinterface, and looks like it is a known issue.
