### ISSUE TITLE
High amount of spawn points causes crash

### ISSUE THREAD

**Issue by TheNewDarkOne** [istornz/iPokeGo#332]
if you have a LOT of spawn points. I'm talking thousands, app pretty much crashes instantly. Somewhere in between a lot and ok, it doesn't crash but moves VERY sluggish. Turning spawn points off can avoid crash and slowness. Spawn points in general need a lot of optimizing and crash fix, especially if https://github.com/istornz/iPokeGo/issues/314 is added when scanning breaks.

**Comment by TheNewDarkOne** [comment]
Actually it looks like it may still be related to this issue

2016-10-03 07:37:51,845 [     Thread-8258][     runserver][   ERROR] Uncaught exception
Traceback (most recent call last):
  File "runserver.py", line 75, in run
    run_old(*args, **kwargs)
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/SocketServer.py", line 602, in process_request_thread
    self.handle_error(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 599, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 657, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 716, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 279, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
2016-10-03 07:37:51,859 [     Thread-8257][     runserver][   ERROR] Uncaught exception
Traceback (most recent call last):
  File "runserver.py", line 75, in run
    run_old(*args, **kwargs)
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/SocketServer.py", line 602, in process_request_thread
    self.handle_error(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 599, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 657, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 716, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 279, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
2016-10-03 07:37:51,872 [     Thread-8252][     runserver][   ERROR] Uncaught exception
Traceback (most recent call last):
  File "runserver.py", line 75, in run
    run_old(*args, **kwargs)
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/SocketServer.py", line 602, in process_request_thread
    self.handle_error(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 599, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 657, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 716, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 279, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])


IE this ticket
https://github.com/istornz/iPokeGo/issues/323

Which I thought I resolved by changing from sqlite to mysql, apparently this problem still occurs but ONLY if "show spawn points" are enabled. if disabled this issue is avoided. it seems it just cannot download the thousands of spawn points I have without crashing the socket and itself.
